stages:
  - stage: dev
    jobs:
      - job: linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - pwsh: script/Invoke-DevDeployment.ps1
      - job: windows
        pool:
          vmImage: windows-latest
        steps:
          - pwsh: script/Invoke-DevTest.ps1
      - job: macos
        pool:
          vmImage: macOS-latest
        steps:
          - pwsh: script/Invoke-DevTest.ps1

  - stage: master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - pwsh: script/Invoke-MasterDeployment.ps1
